'use strict';

/**
 * Datenpunktnamen in allen elf Sprachen, die ioBroker empfiehlt.
 *
 * WARUM EINE EIGENE DATEI
 * In fields.js stehen die Namen als `{ en, de }` - dort gehoeren sie hin, direkt neben Typ,
 * Rolle und Einheit des Feldes. Alle elf Sprachen dort auszuschreiben wuerde jede
 * Felddefinition auf ein Vielfaches aufblaehen und die Feldkunde unlesbar machen. Deshalb
 * die Trennung: fields.js sagt WAS ein Feld ist, diese Datei sagt, wie es in anderen
 * Sprachen heisst. Zusammengefuehrt wird beides in [vollerName].
 *
 * WARUM UEBERHAUPT
 * Der Objektstruktur-Pruefer des ioBroker-Repositories beanstandet jeden Datenpunkt, dessen
 * `common.name` nicht alle elf Sprachen fuehrt (E6001). Am 22.09.2026 waren das 143 von 160
 * Objekten - der gesamte Adapter bis auf die Kanaele.
 *
 * Nachgeschlagen wird ueber den ENGLISCHEN Namen: Er ist in fields.js immer vorhanden und
 * dient hier als Schluessel. Fehlt ein Eintrag, bleibt es bei `{ en, de }` - dann meldet der
 * Pruefer diesen einen Punkt, und der Adapter laeuft trotzdem.
 */

/** Englischer Name -> die neun weiteren Sprachen. en und de kommen aus fields.js. */
const UEBERSETZUNGEN = {
    Power: {
        ru: 'Питание',
        pt: 'Ligar/Desligar',
        nl: 'Aan/uit',
        fr: 'Marche/Arrêt',
        it: 'Accensione',
        es: 'Encendido',
        pl: 'Zasilanie',
        uk: 'Живлення',
        'zh-cn': '电源',
    },
    'Operating mode': {
        ru: 'Режим работы',
        pt: 'Modo de funcionamento',
        nl: 'Bedrijfsmodus',
        fr: 'Mode de fonctionnement',
        it: 'Modalità operativa',
        es: 'Modo de funcionamiento',
        pl: 'Tryb pracy',
        uk: 'Режим роботи',
        'zh-cn': '运行模式',
    },
    'Target temperature': {
        ru: 'Заданная температура',
        pt: 'Temperatura desejada',
        nl: 'Streeftemperatuur',
        fr: 'Température de consigne',
        it: 'Temperatura desiderata',
        es: 'Temperatura objetivo',
        pl: 'Temperatura zadana',
        uk: 'Задана температура',
        'zh-cn': '目标温度',
    },
    'Fan speed': {
        ru: 'Скорость вентилятора',
        pt: 'Velocidade do ventilador',
        nl: 'Ventilatorstand',
        fr: 'Vitesse du ventilateur',
        it: 'Velocità ventola',
        es: 'Velocidad del ventilador',
        pl: 'Prędkość wentylatora',
        uk: 'Швидкість вентилятора',
        'zh-cn': '风扇转速',
    },
    Swing: {
        ru: 'Распределение воздуха',
        pt: 'Distribuição do ar',
        nl: 'Luchtverdeling',
        fr: 'Distribution de l’air',
        it: 'Distribuzione dell’aria',
        es: 'Distribución del aire',
        pl: 'Rozprowadzanie powietrza',
        uk: 'Розподіл повітря',
        'zh-cn': '送风摆动',
    },
    'Swing horizontal': {
        ru: 'Жалюзи горизонтально',
        pt: 'Lamelas na horizontal',
        nl: 'Lamellen horizontaal',
        fr: 'Volets horizontaux',
        it: 'Alette orizzontali',
        es: 'Lamas horizontales',
        pl: 'Żaluzje poziome',
        uk: 'Жалюзі горизонтально',
        'zh-cn': '水平摆风',
    },
    'Swing vertical': {
        ru: 'Жалюзи вертикально',
        pt: 'Lamelas na vertical',
        nl: 'Lamellen verticaal',
        fr: 'Volets verticaux',
        it: 'Alette verticali',
        es: 'Lamas verticales',
        pl: 'Żaluzje pionowe',
        uk: 'Жалюзі вертикально',
        'zh-cn': '垂直摆风',
    },
    Preset: {
        ru: 'Предустановка',
        pt: 'Predefinição',
        nl: 'Voorinstelling',
        fr: 'Préréglage',
        it: 'Preimpostazione',
        es: 'Preajuste',
        pl: 'Ustawienie wstępne',
        uk: 'Передустановка',
        'zh-cn': '预设',
    },
    'Demand control': {
        ru: 'Ограничение мощности',
        pt: 'Limitação de potência',
        nl: 'Vermogensbegrenzing',
        fr: 'Limitation de puissance',
        it: 'Limitazione di potenza',
        es: 'Limitación de potencia',
        pl: 'Ograniczenie mocy',
        uk: 'Обмеження потужності',
        'zh-cn': '功率限制',
    },
    'Econo mode': {
        ru: 'Экономичный режим',
        pt: 'Modo económico',
        nl: 'Spaarstand',
        fr: 'Mode économique',
        it: 'Modalità eco',
        es: 'Modo económico',
        pl: 'Tryb oszczędny',
        uk: 'Економний режим',
        'zh-cn': '节能模式',
    },
    Powerful: {
        ru: 'Турбо',
        pt: 'Turbo',
        nl: 'Turbo',
        fr: 'Turbo',
        it: 'Turbo',
        es: 'Turbo',
        pl: 'Turbo',
        uk: 'Турбо',
        'zh-cn': '强力模式',
    },
    Streamer: {
        ru: 'Очистка воздуха',
        pt: 'Purificação do ar',
        nl: 'Luchtreiniging',
        fr: 'Purification de l’air',
        it: 'Purificazione dell’aria',
        es: 'Purificación del aire',
        pl: 'Oczyszczanie powietrza',
        uk: 'Очищення повітря',
        'zh-cn': '空气净化',
    },
    LED: {
        ru: 'Светодиод дисплея',
        pt: 'LED do visor',
        nl: 'Display-led',
        fr: 'LED d’affichage',
        it: 'LED del display',
        es: 'LED de la pantalla',
        pl: 'Dioda wyświetlacza',
        uk: 'Світлодіод дисплея',
        'zh-cn': '显示灯',
    },
    'Comfort mode': {
        ru: 'Комфортный режим',
        pt: 'Modo conforto',
        nl: 'Comfortstand',
        fr: 'Mode confort',
        it: 'Modalità comfort',
        es: 'Modo confort',
        pl: 'Tryb komfortowy',
        uk: 'Комфортний режим',
        'zh-cn': '舒适模式',
    },
    'Sensor mode': {
        ru: 'Датчик присутствия',
        pt: 'Sensor de presença',
        nl: 'Aanwezigheidssensor',
        fr: 'Détecteur de présence',
        it: 'Sensore di presenza',
        es: 'Sensor de presencia',
        pl: 'Czujnik obecności',
        uk: 'Датчик присутності',
        'zh-cn': '人体感应',
    },
    'Quiet outdoor': {
        ru: 'Тихий режим внешнего блока',
        pt: 'Modo silencioso exterior',
        nl: 'Stille buitenunit',
        fr: 'Mode silencieux extérieur',
        it: 'Modalità silenziosa esterna',
        es: 'Modo silencioso exterior',
        pl: 'Cichy tryb jednostki zewnętrznej',
        uk: 'Тихий режим зовнішнього блока',
        'zh-cn': '室外静音',
    },
    Humidify: {
        ru: 'Увлажнение',
        pt: 'Humidificação',
        nl: 'Bevochtiging',
        fr: 'Humidification',
        it: 'Umidificazione',
        es: 'Humidificación',
        pl: 'Nawilżanie',
        uk: 'Зволоження',
        'zh-cn': '加湿',
    },
    'Anti-freeze active': {
        ru: 'Защита от замерзания включена',
        pt: 'Proteção antigelo ativa',
        nl: 'Vorstbeveiliging actief',
        fr: 'Protection antigel active',
        it: 'Antigelo attivo',
        es: 'Protección antiheladas activa',
        pl: 'Ochrona przeciwzamrożeniowa aktywna',
        uk: 'Захист від замерзання активний',
        'zh-cn': '防冻保护启用',
    },
    'Automatic control': {
        ru: 'Автоматическое управление',
        pt: 'Controlo automático',
        nl: 'Automatische regeling',
        fr: 'Commande automatique',
        it: 'Controllo automatico',
        es: 'Control automático',
        pl: 'Sterowanie automatyczne',
        uk: 'Автоматичне керування',
        'zh-cn': '自动控制',
    },
    'Automation: switch-on time (HHMM)': {
        ru: 'Автоматика: время включения (ЧЧММ)',
        pt: 'Automatismo: hora de ligar (HHMM)',
        nl: 'Automaat: inschakeltijd (UUMM)',
        fr: 'Automatisme : heure de mise en marche (HHMM)',
        it: 'Automatismo: ora di accensione (HHMM)',
        es: 'Automatismo: hora de encendido (HHMM)',
        pl: 'Automatyka: godzina włączenia (GGMM)',
        uk: 'Автоматика: час увімкнення (ГГХХ)',
        'zh-cn': '自动化：开机时间（HHMM）',
    },
    'Automation: switch-off time (HHMM)': {
        ru: 'Автоматика: время выключения (ЧЧММ)',
        pt: 'Automatismo: hora de desligar (HHMM)',
        nl: 'Automaat: uitschakeltijd (UUMM)',
        fr: 'Automatisme : heure d’arrêt (HHMM)',
        it: 'Automatismo: ora di spegnimento (HHMM)',
        es: 'Automatismo: hora de apagado (HHMM)',
        pl: 'Automatyka: godzina wyłączenia (GGMM)',
        uk: 'Автоматика: час вимкнення (ГГХХ)',
        'zh-cn': '自动化：关机时间（HHMM）',
    },
    'Automation: target temperature': {
        ru: 'Автоматика: целевая температура',
        pt: 'Automatismo: temperatura alvo',
        nl: 'Automaat: streeftemperatuur',
        fr: 'Automatisme : température cible',
        it: 'Automatismo: temperatura obiettivo',
        es: 'Automatismo: temperatura objetivo',
        pl: 'Automatyka: temperatura docelowa',
        uk: 'Автоматика: цільова температура',
        'zh-cn': '自动化：目标温度',
    },

    // ---------------------------------------------------------------- Messwerte
    'Unit setpoint': {
        ru: 'Заданное значение установки',
        pt: 'Valor nominal da unidade',
        nl: 'Instelwaarde van de unit',
        fr: 'Consigne de l’unité',
        it: 'Setpoint dell’unità',
        es: 'Consigna de la unidad',
        pl: 'Wartość zadana jednostki',
        uk: 'Задане значення установки',
        'zh-cn': '机组设定值',
    },
    'Indoor humidity': {
        ru: 'Влажность в помещении',
        pt: 'Humidade interior',
        nl: 'Luchtvochtigheid binnen',
        fr: 'Humidité intérieure',
        it: 'Umidità interna',
        es: 'Humedad interior',
        pl: 'Wilgotność wewnątrz',
        uk: 'Вологість у приміщенні',
        'zh-cn': '室内湿度',
    },
    'Inlet temperature': {
        ru: 'Температура на входе',
        pt: 'Temperatura de aspiração',
        nl: 'Aanzuigtemperatuur',
        fr: 'Température d’aspiration',
        it: 'Temperatura di aspirazione',
        es: 'Temperatura de aspiración',
        pl: 'Temperatura zasysania',
        uk: 'Температура всмоктування',
        'zh-cn': '进风温度',
    },
    'Outside temperature': {
        ru: 'Наружная температура',
        pt: 'Temperatura exterior',
        nl: 'Buitentemperatuur',
        fr: 'Température extérieure',
        it: 'Temperatura esterna',
        es: 'Temperatura exterior',
        pl: 'Temperatura zewnętrzna',
        uk: 'Зовнішня температура',
        'zh-cn': '室外温度',
    },
    'External reference temperature': {
        ru: 'Внешняя эталонная температура',
        pt: 'Temperatura de referência externa',
        nl: 'Externe referentietemperatuur',
        fr: 'Température de référence externe',
        it: 'Temperatura di riferimento esterna',
        es: 'Temperatura de referencia externa',
        pl: 'Zewnętrzna temperatura odniesienia',
        uk: 'Зовнішня еталонна температура',
        'zh-cn': '外部参考温度',
    },
    'Refrigerant temperature': {
        ru: 'Температура хладагента',
        pt: 'Temperatura do refrigerante',
        nl: 'Koudemiddeltemperatuur',
        fr: 'Température du fluide frigorigène',
        it: 'Temperatura del refrigerante',
        es: 'Temperatura del refrigerante',
        pl: 'Temperatura czynnika chłodniczego',
        uk: 'Температура холодоагенту',
        'zh-cn': '制冷剂温度',
    },
    'Compressor speed': {
        ru: 'Частота вращения компрессора',
        pt: 'Rotação do compressor',
        nl: 'Compressortoerental',
        fr: 'Régime du compresseur',
        it: 'Numero di giri del compressore',
        es: 'Régimen del compresor',
        pl: 'Prędkość obrotowa sprężarki',
        uk: 'Частота обертання компресора',
        'zh-cn': '压缩机转速',
    },
    'Louvre angle': {
        ru: 'Угол жалюзи',
        pt: 'Ângulo das lamelas',
        nl: 'Lamelhoek',
        fr: 'Angle des volets',
        it: 'Angolo delle alette',
        es: 'Ángulo de las lamas',
        pl: 'Kąt żaluzji',
        uk: 'Кут жалюзі',
        'zh-cn': '导风板角度',
    },
    Flap: {
        ru: 'Заслонка',
        pt: 'Aba',
        nl: 'Klep',
        fr: 'Volet',
        it: 'Deflettore',
        es: 'Compuerta',
        pl: 'Klapa',
        uk: 'Заслінка',
        'zh-cn': '风门',
    },
    Heating: {
        ru: 'Нагрев',
        pt: 'Aquecimento',
        nl: 'Verwarmen',
        fr: 'Chauffage',
        it: 'Riscaldamento',
        es: 'Calefacción',
        pl: 'Grzanie',
        uk: 'Нагрів',
        'zh-cn': '制热中',
    },
    'Controlled by other unit': {
        ru: 'Управляется другим блоком',
        pt: 'Controlado por outra unidade',
        nl: 'Aangestuurd door andere unit',
        fr: 'Piloté par une autre unité',
        it: 'Controllato da un’altra unità',
        es: 'Controlado por otra unidad',
        pl: 'Sterowane przez inną jednostkę',
        uk: 'Керується іншим блоком',
        'zh-cn': '由其他机组控制',
    },
    'Air conditioner online': {
        ru: 'Кондиционер на связи',
        pt: 'Ar condicionado acessível',
        nl: 'Airco bereikbaar',
        fr: 'Climatiseur joignable',
        it: 'Climatizzatore raggiungibile',
        es: 'Aire acondicionado accesible',
        pl: 'Klimatyzator osiągalny',
        uk: 'Кондиціонер доступний',
        'zh-cn': '空调在线',
    },
    'Power consumption': {
        ru: 'Текущая мощность',
        pt: 'Potência instantânea',
        nl: 'Momentaan vermogen',
        fr: 'Puissance instantanée',
        it: 'Potenza istantanea',
        es: 'Potencia instantánea',
        pl: 'Moc chwilowa',
        uk: 'Миттєва потужність',
        'zh-cn': '当前功率',
    },
    'Lifetime energy': {
        ru: 'Энергия всего',
        pt: 'Energia total',
        nl: 'Energie totaal',
        fr: 'Énergie totale',
        it: 'Energia totale',
        es: 'Energía total',
        pl: 'Energia łącznie',
        uk: 'Енергія загалом',
        'zh-cn': '累计用电量',
    },
    'Lifetime heating energy': {
        ru: 'Энергия на нагрев',
        pt: 'Energia de aquecimento',
        nl: 'Energie verwarmen',
        fr: 'Énergie de chauffage',
        it: 'Energia di riscaldamento',
        es: 'Energía de calefacción',
        pl: 'Energia grzania',
        uk: 'Енергія на нагрів',
        'zh-cn': '制热用电量',
    },
    'Lifetime cooling energy': {
        ru: 'Энергия на охлаждение',
        pt: 'Energia de arrefecimento',
        nl: 'Energie koelen',
        fr: 'Énergie de refroidissement',
        it: 'Energia di raffreddamento',
        es: 'Energía de refrigeración',
        pl: 'Energia chłodzenia',
        uk: 'Енергія на охолодження',
        'zh-cn': '制冷用电量',
    },
    Protocol: {
        ru: 'Протокол',
        pt: 'Protocolo',
        nl: 'Protocol',
        fr: 'Protocole',
        it: 'Protocollo',
        es: 'Protocolo',
        pl: 'Protokół',
        uk: 'Протокол',
        'zh-cn': '协议',
    },
    Model: {
        ru: 'Модель',
        pt: 'Modelo',
        nl: 'Model',
        fr: 'Modèle',
        it: 'Modello',
        es: 'Modelo',
        pl: 'Model',
        uk: 'Модель',
        'zh-cn': '型号',
    },
    'Last message': {
        ru: 'Последнее сообщение',
        pt: 'Última mensagem',
        nl: 'Laatste bericht',
        fr: 'Dernier message',
        it: 'Ultimo messaggio',
        es: 'Último mensaje',
        pl: 'Ostatni komunikat',
        uk: 'Останнє повідомлення',
        'zh-cn': '最后消息',
    },

    'Room temperature (external sensor if present)': {
        ru: 'Температура в помещении (внешний датчик, если есть)',
        pt: 'Temperatura ambiente (sensor externo, se existir)',
        nl: 'Kamertemperatuur (externe sensor indien aanwezig)',
        fr: 'Température ambiante (capteur externe si présent)',
        it: 'Temperatura ambiente (sensore esterno se presente)',
        es: 'Temperatura ambiente (sensor externo si lo hay)',
        pl: 'Temperatura pomieszczenia (czujnik zewnętrzny, jeśli jest)',
        uk: 'Температура в приміщенні (зовнішній датчик, якщо є)',
        'zh-cn': '室温（如有外部传感器）',
    },
    "Room temperature (unit's own sensor)": {
        ru: 'Температура в помещении (собственный датчик)',
        pt: 'Temperatura ambiente (sensor do aparelho)',
        nl: 'Kamertemperatuur (eigen sensor)',
        fr: 'Température ambiante (capteur de l’appareil)',
        it: 'Temperatura ambiente (sensore dell’apparecchio)',
        es: 'Temperatura ambiente (sensor del aparato)',
        pl: 'Temperatura pomieszczenia (czujnik urządzenia)',
        uk: 'Температура в приміщенні (власний датчик)',
        'zh-cn': '室温（机组自带传感器）',
    },
    'Faikout automation (timed and temperature switching)': {
        ru: 'Автоматика Faikout (по времени и температуре)',
        pt: 'Automatismo Faikout (por hora e temperatura)',
        nl: 'Faikout-automaat (tijd- en temperatuurschakeling)',
        fr: 'Automatisme Faikout (horaire et température)',
        it: 'Automatismo Faikout (a tempo e temperatura)',
        es: 'Automatismo Faikout (por hora y temperatura)',
        pl: 'Automatyka Faikout (czasowa i temperaturowa)',
        uk: 'Автоматика Faikout (за часом і температурою)',
        'zh-cn': 'Faikout 自动化（定时与温控）',
    },
    'Automation: switch by temperature': {
        ru: 'Автоматика: переключение по температуре',
        pt: 'Automatismo: comutação por temperatura',
        nl: 'Automaat: schakelen op temperatuur',
        fr: 'Automatisme : commutation selon la température',
        it: 'Automatismo: commutazione in base alla temperatura',
        es: 'Automatismo: conmutación por temperatura',
        pl: 'Automatyka: przełączanie według temperatury',
        uk: 'Автоматика: перемикання за температурою',
        'zh-cn': '自动化：按温度切换',
    },
    'Automation: tolerance around target (0 = module does not control)': {
        ru: 'Автоматика: допуск вокруг заданного значения (0 = модуль не регулирует)',
        pt: 'Automatismo: tolerância em torno do valor alvo (0 = o módulo não regula)',
        nl: 'Automaat: tolerantie rond de streefwaarde (0 = module regelt niet)',
        fr: 'Automatisme : tolérance autour de la consigne (0 = le module ne régule pas)',
        it: 'Automatismo: tolleranza attorno al valore obiettivo (0 = il modulo non regola)',
        es: 'Automatismo: tolerancia alrededor del valor objetivo (0 = el módulo no regula)',
        pl: 'Automatyka: tolerancja wokół wartości zadanej (0 = moduł nie reguluje)',
        uk: 'Автоматика: допуск навколо заданого значення (0 = модуль не регулює)',
        'zh-cn': '自动化：目标值容差（0 = 模块不调节）',
    },

    // ---------------------------------------------------------------- Modulzustand
    'Module online': {
        ru: 'Модуль на связи',
        pt: 'Módulo acessível',
        nl: 'Module bereikbaar',
        fr: 'Module joignable',
        it: 'Modulo raggiungibile',
        es: 'Módulo accesible',
        pl: 'Moduł osiągalny',
        uk: 'Модуль доступний',
        'zh-cn': '模块在线',
    },
    'IP address': {
        ru: 'IP-адрес',
        pt: 'Endereço IP',
        nl: 'IP-adres',
        fr: 'Adresse IP',
        it: 'Indirizzo IP',
        es: 'Dirección IP',
        pl: 'Adres IP',
        uk: 'IP-адреса',
        'zh-cn': 'IP 地址',
    },
    'Device ID': {
        ru: 'Идентификатор устройства',
        pt: 'ID do dispositivo',
        nl: 'Apparaat-ID',
        fr: 'Identifiant de l’appareil',
        it: 'ID del dispositivo',
        es: 'ID del dispositivo',
        pl: 'Identyfikator urządzenia',
        uk: 'Ідентифікатор пристрою',
        'zh-cn': '设备 ID',
    },
    'WiFi network': {
        ru: 'Сеть Wi-Fi',
        pt: 'Rede Wi-Fi',
        nl: 'Wifi-netwerk',
        fr: 'Réseau Wi-Fi',
        it: 'Rete Wi-Fi',
        es: 'Red Wi-Fi',
        pl: 'Sieć Wi-Fi',
        uk: 'Мережа Wi-Fi',
        'zh-cn': 'Wi-Fi 网络',
    },
    'WiFi BSSID': {
        ru: 'BSSID Wi-Fi',
        pt: 'BSSID Wi-Fi',
        nl: 'Wifi-BSSID',
        fr: 'BSSID Wi-Fi',
        it: 'BSSID Wi-Fi',
        es: 'BSSID Wi-Fi',
        pl: 'BSSID Wi-Fi',
        uk: 'BSSID Wi-Fi',
        'zh-cn': 'Wi-Fi BSSID',
    },
    'WiFi channel': {
        ru: 'Канал Wi-Fi',
        pt: 'Canal Wi-Fi',
        nl: 'Wifi-kanaal',
        fr: 'Canal Wi-Fi',
        it: 'Canale Wi-Fi',
        es: 'Canal Wi-Fi',
        pl: 'Kanał Wi-Fi',
        uk: 'Канал Wi-Fi',
        'zh-cn': 'Wi-Fi 信道',
    },
    'WiFi signal': {
        ru: 'Уровень сигнала Wi-Fi',
        pt: 'Sinal Wi-Fi',
        nl: 'Wifi-signaal',
        fr: 'Signal Wi-Fi',
        it: 'Segnale Wi-Fi',
        es: 'Señal Wi-Fi',
        pl: 'Sygnał Wi-Fi',
        uk: 'Сигнал Wi-Fi',
        'zh-cn': 'Wi-Fi 信号',
    },
    Uptime: {
        ru: 'Время работы',
        pt: 'Tempo de funcionamento',
        nl: 'Bedrijfstijd',
        fr: 'Durée de fonctionnement',
        it: 'Tempo di funzionamento',
        es: 'Tiempo de funcionamiento',
        pl: 'Czas pracy',
        uk: 'Час роботи',
        'zh-cn': '运行时间',
    },
    'MQTT uptime': {
        ru: 'Время работы MQTT',
        pt: 'Tempo de ligação MQTT',
        nl: 'MQTT-bedrijfstijd',
        fr: 'Durée de connexion MQTT',
        it: 'Tempo di connessione MQTT',
        es: 'Tiempo de conexión MQTT',
        pl: 'Czas połączenia MQTT',
        uk: 'Час роботи MQTT',
        'zh-cn': 'MQTT 运行时间',
    },
    'Firmware version': {
        ru: 'Версия прошивки',
        pt: 'Versão do firmware',
        nl: 'Firmwareversie',
        fr: 'Version du micrologiciel',
        it: 'Versione del firmware',
        es: 'Versión del firmware',
        pl: 'Wersja oprogramowania',
        uk: 'Версія прошивки',
        'zh-cn': '固件版本',
    },
    'Firmware build': {
        ru: 'Сборка прошивки',
        pt: 'Compilação do firmware',
        nl: 'Firmware-build',
        fr: 'Build du micrologiciel',
        it: 'Build del firmware',
        es: 'Compilación del firmware',
        pl: 'Kompilacja oprogramowania',
        uk: 'Збірка прошивки',
        'zh-cn': '固件版本号',
    },
    'Hardware variant': {
        ru: 'Вариант оборудования',
        pt: 'Variante de hardware',
        nl: 'Hardwarevariant',
        fr: 'Variante matérielle',
        it: 'Variante hardware',
        es: 'Variante de hardware',
        pl: 'Wariant sprzętu',
        uk: 'Варіант обладнання',
        'zh-cn': '硬件型号',
    },
    Application: {
        ru: 'Приложение',
        pt: 'Aplicação',
        nl: 'Toepassing',
        fr: 'Application',
        it: 'Applicazione',
        es: 'Aplicación',
        pl: 'Aplikacja',
        uk: 'Застосунок',
        'zh-cn': '应用程序',
    },
    'Flash size': {
        ru: 'Объём флеш-памяти',
        pt: 'Tamanho da flash',
        nl: 'Flashgrootte',
        fr: 'Taille de la flash',
        it: 'Dimensione della flash',
        es: 'Tamaño de la flash',
        pl: 'Rozmiar pamięci flash',
        uk: 'Обсяг флеш-пам’яті',
        'zh-cn': '闪存容量',
    },
    'Free memory': {
        ru: 'Свободная память',
        pt: 'Memória livre',
        nl: 'Vrij geheugen',
        fr: 'Mémoire libre',
        it: 'Memoria libera',
        es: 'Memoria libre',
        pl: 'Wolna pamięć',
        uk: 'Вільна пам’ять',
        'zh-cn': '可用内存',
    },
    'Free SPI RAM': {
        ru: 'Свободная SPI-память',
        pt: 'Memória SPI livre',
        nl: 'Vrij SPI-geheugen',
        fr: 'Mémoire SPI libre',
        it: 'Memoria SPI libera',
        es: 'Memoria SPI libre',
        pl: 'Wolna pamięć SPI',
        uk: 'Вільна пам’ять SPI',
        'zh-cn': '可用 SPI 内存',
    },
    'Reset reason': {
        ru: 'Причина перезапуска',
        pt: 'Motivo do reinício',
        nl: 'Reden van herstart',
        fr: 'Cause du redémarrage',
        it: 'Motivo del riavvio',
        es: 'Motivo del reinicio',
        pl: 'Przyczyna restartu',
        uk: 'Причина перезапуску',
        'zh-cn': '重启原因',
    },

    // ---------------------------------------------------------------- Verbrauch
    Consumption: {
        ru: 'Потребление',
        pt: 'Consumo',
        nl: 'Verbruik',
        fr: 'Consommation',
        it: 'Consumo',
        es: 'Consumo',
        pl: 'Zużycie',
        uk: 'Споживання',
        'zh-cn': '用电量',
    },
    Total: {
        ru: 'Всего',
        pt: 'Total',
        nl: 'Totaal',
        fr: 'Total',
        it: 'Totale',
        es: 'Total',
        pl: 'Łącznie',
        uk: 'Загалом',
        'zh-cn': '合计',
    },
    Cooling: {
        ru: 'Охлаждение',
        pt: 'Arrefecimento',
        nl: 'Koelen',
        fr: 'Refroidissement',
        it: 'Raffreddamento',
        es: 'Refrigeración',
        pl: 'Chłodzenie',
        uk: 'Охолодження',
        'zh-cn': '制冷',
    },
    'Current hour': {
        ru: 'Текущий час',
        pt: 'Hora atual',
        nl: 'Huidig uur',
        fr: 'Heure en cours',
        it: 'Ora corrente',
        es: 'Hora actual',
        pl: 'Bieżąca godzina',
        uk: 'Поточна година',
        'zh-cn': '当前小时',
    },
    'Last full hour': {
        ru: 'Последний полный час',
        pt: 'Última hora completa',
        nl: 'Laatste volle uur',
        fr: 'Dernière heure complète',
        it: 'Ultima ora completa',
        es: 'Última hora completa',
        pl: 'Ostatnia pełna godzina',
        uk: 'Остання повна година',
        'zh-cn': '上一整点小时',
    },
    Today: {
        ru: 'Сегодня',
        pt: 'Hoje',
        nl: 'Vandaag',
        fr: 'Aujourd’hui',
        it: 'Oggi',
        es: 'Hoy',
        pl: 'Dzisiaj',
        uk: 'Сьогодні',
        'zh-cn': '今天',
    },
    Yesterday: {
        ru: 'Вчера',
        pt: 'Ontem',
        nl: 'Gisteren',
        fr: 'Hier',
        it: 'Ieri',
        es: 'Ayer',
        pl: 'Wczoraj',
        uk: 'Учора',
        'zh-cn': '昨天',
    },
    'This month': {
        ru: 'Текущий месяц',
        pt: 'Este mês',
        nl: 'Deze maand',
        fr: 'Ce mois-ci',
        it: 'Questo mese',
        es: 'Este mes',
        pl: 'Bieżący miesiąc',
        uk: 'Цей місяць',
        'zh-cn': '本月',
    },
    'Last month': {
        ru: 'Прошлый месяц',
        pt: 'Mês passado',
        nl: 'Vorige maand',
        fr: 'Mois dernier',
        it: 'Mese scorso',
        es: 'Mes pasado',
        pl: 'Poprzedni miesiąc',
        uk: 'Минулий місяць',
        'zh-cn': '上月',
    },
    'Last 48 hours (JSON)': {
        ru: 'Последние 48 часов (JSON)',
        pt: 'Últimas 48 horas (JSON)',
        nl: 'Laatste 48 uur (JSON)',
        fr: 'Dernières 48 heures (JSON)',
        it: 'Ultime 48 ore (JSON)',
        es: 'Últimas 48 horas (JSON)',
        pl: 'Ostatnie 48 godzin (JSON)',
        uk: 'Останні 48 годин (JSON)',
        'zh-cn': '最近 48 小时（JSON）',
    },
    'Last 62 days (JSON)': {
        ru: 'Последние 62 дня (JSON)',
        pt: 'Últimos 62 dias (JSON)',
        nl: 'Laatste 62 dagen (JSON)',
        fr: 'Derniers 62 jours (JSON)',
        it: 'Ultimi 62 giorni (JSON)',
        es: 'Últimos 62 días (JSON)',
        pl: 'Ostatnie 62 dni (JSON)',
        uk: 'Останні 62 дні (JSON)',
        'zh-cn': '最近 62 天（JSON）',
    },
    'Last 24 months (JSON)': {
        ru: 'Последние 24 месяца (JSON)',
        pt: 'Últimos 24 meses (JSON)',
        nl: 'Laatste 24 maanden (JSON)',
        fr: 'Derniers 24 mois (JSON)',
        it: 'Ultimi 24 mesi (JSON)',
        es: 'Últimos 24 meses (JSON)',
        pl: 'Ostatnie 24 miesiące (JSON)',
        uk: 'Останні 24 місяці (JSON)',
        'zh-cn': '最近 24 个月（JSON）',
    },

    // ---------------------------------------------------------------- Kanaele und Instanz
    Control: {
        ru: 'Управление',
        pt: 'Controlo',
        nl: 'Besturing',
        fr: 'Commande',
        it: 'Comando',
        es: 'Control',
        pl: 'Sterowanie',
        uk: 'Керування',
        'zh-cn': '控制',
    },
    Readings: {
        ru: 'Измеренные значения',
        pt: 'Valores medidos',
        nl: 'Meetwaarden',
        fr: 'Valeurs mesurées',
        it: 'Valori misurati',
        es: 'Valores medidos',
        pl: 'Wartości pomiarowe',
        uk: 'Виміряні значення',
        'zh-cn': '测量值',
    },
    'Device info': {
        ru: 'Сведения об устройстве',
        pt: 'Informação do dispositivo',
        nl: 'Apparaatinformatie',
        fr: 'Informations sur l’appareil',
        it: 'Informazioni sul dispositivo',
        es: 'Información del dispositivo',
        pl: 'Informacje o urządzeniu',
        uk: 'Відомості про пристрій',
        'zh-cn': '设备信息',
    },
    'Device connected': {
        ru: 'Устройство подключено',
        pt: 'Dispositivo ligado',
        nl: 'Apparaat verbonden',
        fr: 'Appareil connecté',
        it: 'Dispositivo connesso',
        es: 'Dispositivo conectado',
        pl: 'Urządzenie połączone',
        uk: 'Пристрій підключено',
        'zh-cn': '设备已连接',
    },
};

/**
 * Aus `{ en, de }` das vollstaendige i18n-Objekt machen.
 *
 * Ist der Name schon vollstaendig oder gibt es keine Uebersetzung, bleibt er unveraendert -
 * ein fehlender Eintrag soll den Adapter nicht aufhalten.
 *
 * @param {object|string} name Name aus der Felddefinition
 * @returns {object|string} Name in allen elf Sprachen, soweit bekannt
 */
function vollerName(name) {
    if (!name || typeof name !== 'object' || !name.en) {
        return name;
    }
    const weitere = UEBERSETZUNGEN[name.en];
    return weitere ? { ...name, ...weitere } : name;
}

/**
 * Welche englischen Namen noch keine Uebersetzung haben - fuer den Test.
 *
 * @param {object[]} namen  Namen aus den Felddefinitionen
 * @returns {string[]} englische Namen ohne Eintrag in [UEBERSETZUNGEN]
 */
function ohneUebersetzung(namen) {
    return namen.filter(n => n && n.en && !UEBERSETZUNGEN[n.en]).map(n => n.en);
}

module.exports = { UEBERSETZUNGEN, vollerName, ohneUebersetzung };
